### ISSUE TITLE
Fix tslint errors

### ISSUE THREAD

**Issue by poush** [h2org/h2-core#14]
Right now there are few linting errors in the source code. Just run `npm run lint` and it will print all those errors. Fix those errors, you can also use some extension on your editor to fix them automatically. 

If you have any ideas to put an auto fix on pre-commit, please feel free to put here.

**Comment by Muskan0510** [comment]
Hello, I'm interested in this issue. 
For autofixing on pre-commit, can we use TSLint or ESLint git pre-commit hooks using husky?
