### ISSUE TITLE
Create a basic CI file

### ISSUE THREAD

**Issue by poush** [h2org/h2-core#8]
In this task, a basic Travis CI file needs to be created. The name of the file will be `.travis.yml`  and for now, we need basic checks only. It should run `tsc` command. 

You can try to improve with more checks but for now `tsc` is required.

**Comment by divija-palleti** [comment]
Just to clarify you wanted a tsc command on the existing YAML file right?

**Comment by poush** [comment]
I forgot that the old Travis file was still there in the codebase.  Can you also remove `npm run test` 
and instead, put `npm run lint`  and  `tsc`  in respective order.

**Comment by asciarp08** [comment]
Do we need to add the Travis badge, if so, can I get the link?

**Comment by divija-palleti** [comment]
Done!

**Comment by divija-palleti** [comment]
> I forgot that the old Travis file was still there in the codebase. Can you also remove `npm run test`
> and instead, put `npm run lint` and `tsc` in respective order.

Done!
